### ISSUE TITLE
i.spectrum is not a function

### ISSUE THREAD

**Issue by pburrows** [Jimdo/angular-spectrum-colorpicker#43]
I receive the following two errors

```javascript
TypeError: i.spectrum is not a function
    at link (http://localhost:19812/jspm_packages/github/jimdo/angular-spectrum-colorpicker@1.4.2/dist/angular-spectrum-colorpicker.min.js:2:1411)
    at http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:8786:44
    at invokeLinkFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:8792:9)
    at nodeLinkFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:8292:11)
    at delayedNodeLinkFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:8540:11)
    at compositeLinkFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:7683:13)
    at compositeLinkFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:7687:13)
    at publicLinkFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:7558:30)
    at boundTranscludeFn (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:7702:16)
    at controllersBoundTransclude (http://localhost:19812/jspm_packages/github/angular/bower-angular@1.4.7/angular.js:8319:18) <span ng-model="yourFancyModel" class="ng-isolate-scope">(anonymous function) @ angular.js:12480(anonymous function) @ angular.js:9249invokeLinkFn @ angular.js:8794nodeLinkFn @ angular.js:8292delayedNodeLinkFn @ angular.js:8540compositeLinkFn @ angular.js:7683compositeLinkFn @ angular.js:7687publicLinkFn @ angular.js:7558boundTranscludeFn @ angular.js:7702controllersBoundTransclude @ angular.js:8319ngDirective.link @ angular.js:28144invokeLinkFn @ angular.js:8792nodeLinkFn @ angular.js:8292compositeLinkFn @ angular.js:7683nodeLinkFn @ angular.js:8287compositeLinkFn @ angular.js:7683nodeLinkFn @ angular.js:8287delayedNodeLinkFn @ angular.js:8540compositeLinkFn @ angular.js:7683publicLinkFn @ angular.js:7558boundTranscludeFn @ angular.js:7702controllersBoundTransclude @ angular.js:8319ngDirective.link @ angular.js:28144invokeLinkFn @ angular.js:8792nodeLinkFn @ angular.js:8292compositeLinkFn @ angular.js:7683nodeLinkFn @ angular.js:8287(anonymous function) @ angular.js:8522processQueue @ angular.js:14748(anonymous function) @ angular.js:14764Scope.$eval @ angular.js:15992Scope.$digest @ angular.js:15803Scope.$apply @ angular.js:16100done @ angular.js:10549completeRequest @ angular.js:10747requestLoaded @ angular.js:10688XMLHttpRequest.send (async)(anonymous function) @ angular.js:10725sendReq @ angular.js:10518serverRequest @ angular.js:10225processQueue @ angular.js:14748(anonymous function) @ angular.js:14764Scope.$eval @ angular.js:15992Scope.$digest @ angular.js:15803Scope.$apply @ angular.js:16100done @ angular.js:10549completeRequest @ angular.js:10747requestLoaded @ angular.js:10688XMLHttpRequest.send (async)(anonymous function) @ angular.js:10725sendReq @ angular.js:10518serverRequest @ angular.js:10225processQueue @ angular.js:14748(anonymous function) @ angular.js:14764Scope.$eval @ angular.js:15992Scope.$digest @ angular.js:15803Scope.$apply @ angular.js:16100bootstrapApply @ angular.js:1663invoke @ angular.js:4481doBootstrap @ angular.js:1661bootstrap @ angular.js:1681angularInit @ angular.js:1575(anonymous function) @ angular.js:28902trigger @ angular.js:3027setTimeout (async)JQLite.ready @ angular.js:3032(anonymous function) @ angular.js:28901(anonymous function) @ angular.js:28905U @ system.js:4o.execute @ system.js:5i @ system.js:4s @ system.js:4(anonymous function) @ system.js:4(anonymous function) @ bower-angular@1.4.7.js:1(anonymous function) @ bower-angular@1.4.7.js:2U @ system.js:4c.execute @ system.js:5i @ system.js:4n @ system.js:4execute @ system.js:5b @ system.js:4w @ system.js:4p @ system.js:4h @ system.js:4(anonymous function) @ system.js:4Promise.resolve (async)(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:5(anonymous function) @ system.js:4
```
and
```javascript
angular.js:12480 TypeError: i.spectrum is not a function
    at e.$render (angular-spectrum-colorpicker.min.js:2)
    at Object.ngModelWatch (angular.js:25426)
    at Scope.$digest (angular.js:15821)
    at Scope.$apply (angular.js:16100)
    at done (angular.js:10549)
    at completeRequest (angular.js:10747)
    at XMLHttpRequest.requestLoaded (angular.js:10688)
```

when I attempt to load and run the color picker like this:

```javascript
import angular from "angular";
import 'angular-ui-router';
import 'angular-bootstrap';
import 'jquery';
import 'angular-spectrum-colorpicker';
import '../lib/spectrum/spectrum.js';

var MyApp = angular.module("MyApp ", [
   "ui.router",
   "ui.bootstrap",
   'angularSpectrumColorpicker'
]);
```

I am sure the issue is simply my ignorance. Can someone let me know what i am doing wrong?

**Comment by Xiphe** [comment]
try to load spectrum before the angular colorpicker

**Comment by Xiphe** [comment]
any progress here?

**Comment by pburrows** [comment]
Yes. To get it to work I had to modify the dist/angular-spectrum-colorpicker.min.js file. I added this as the first line of that file:

    import "spectrum";

**Comment by Xiphe** [comment]
ok then, the error was because of loading order then.

Since we're not using any module system in our code (yet), we can only rely on asset pipelines to to interpret the [bower dependencies](https://github.com/Jimdo/angular-spectrum-colorpicker/blob/master/bower.json#L41) correctly.

If your asset management can not do that (don't worry, our's refuses to do so, too) you need to manually do this when you bootstrap the application.

Example:
```js
// angular-spectrum-colorpicker dependencies
import angular from "angular";
import '../lib/spectrum/spectrum.js';
// ...
// the lib itself
import 'angular-spectrum-colorpicker';
```

when your solution works for you, thats fine, too. but modifying external component code is something i would try to avoid in general.

**Comment by ri0t** [comment]
Heya. I get the same problems. I'm even loading the spectrum-colorpicker in my core module and have it working. 
I can add a colorpicker by using jquery, yet the same message as above appears, when trying to use this via angular-schema-form-colorpicker or simply by inserting a <spectrum-colorpicker>... Using webpack.
I'm pretty sure it has something to do with angular's injection stuff (which is real big PITA, i sure hope that is sorted with 2.x)..

**Comment by Xiphe** [comment]
this is the repo for `angular-spectrum-colorpicker` and not `angular-schema-form-colorpicker` (see https://github.com/Textalk/angular-schema-form-colorpicker).

anyway: angular's dependency injection starts to do its magic *after* all JS has been loaded. This issue was caused by incorrect loading order

**Comment by abhijitmabhi** [comment]
Unless and until the problem in order, it will not be solved the issue. Try to load spectrum before angular colorpicker anyhow. It works for me.
